version: '3.8'

services:
  emby-controller:
    image: ghcr.io/jkjoy/emby-controller:latest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    container_name: emby-controller
    restart: unless-stopped
    # 与下方 mysql 服务的数据库名、密码保持一致。
    environment:
      DB_DRIVER: "mysql"
      DB_TYPE: "mysql"
      DB_HOST: "mysql"
      DB_NAME: "randallanjie"
      DB_USER: "root"
      DB_PASS: "root"
      DB_PORT: "3306"
      DB_CHARSET: "utf8mb4"
      DB_PREFIX: "rc_"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:2347:2347"
    depends_on:
      - mysql
    networks:
      - emby-network

  mysql:
    image: mysql:8.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    container_name: emby-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: randallanjie
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./demomedia_2025-02-14.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - emby-network

networks:
  emby-network:
    driver: bridge

volumes:
  mysql_data:
