services:
  emby-controller:
    image: ghcr.io/jkjoy/emby-controller:latest
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:2347:2347"
    depends_on:
      - db
  db:
    image: mysql:8.1.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --explicit_defaults_for_timestamp=true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=emby
      - MYSQL_DATABASE=emby
