# ThinkPHP（含子应用、按月目录）、自定义日志和 Workerman 日志
/app/runtime/log/*.log /app/runtime/log/*/*.log /app/runtime/*/log/*.log /app/runtime/*/log/*/*.log /app/app/runtime/log/*.log /app/vendor/workerman/workerman.log {
    daily
    maxsize 10M
    rotate 3
    maxage 7
    missingok
    notifempty
    compress
    copytruncate
    su root root
}
